"""
check_facts.py
--------------
Guards the one discipline that keeps the written deliverables trustworthy:

    no number appears in REPORT.md or SLIDES.md unless it came from facts.json

Every figure in those documents is generated by make_figures.py, which imports
the live backend. If a number is edited by hand, or the data refreshes and the
prose is not regenerated, this catches the drift.

    python docs/check_facts.py

Exits non-zero if any numeric token in the prose cannot be matched to a value
in facts.json.
"""

import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
FACTS_PATH = os.path.join(HERE, "figures", "facts.json")
DOCS = ["REPORT.md", "SLIDES.md", "PRESENTATION_PARTS.md"]

# Numbers that are structural rather than empirical: section numbers, years,
# lag indices, percentages of a whole, and the small integers that appear in
# model orders and test lags. Checking these adds noise, not safety.
IGNORE = {
    # counts, orders, lags, small structural integers
    *{str(i) for i in range(0, 101)},
    "1970", "1973", "1982", "1986", "1992", "1995", "1969", "2021",  # citations
    "2015", "2026", "16", "12", "10", "5", "3", "1",
    "0.05", "0.01", "1.0", "3.0", "95", "80",
}


# A comma is only a thousands separator when followed by exactly three digits.
# Without that restriction an ARIMA order like "(1,1,3)" is read as the number
# 113, which is how this checker first "failed".
NUM = re.compile(r"(?<![\w.,])[-−]?\d{1,3}(?:,\d{3})+(?:\.\d+)?|(?<![\w.,])[-−]?\d+(?:\.\d+)?")


def numbers_in(text: str) -> set[str]:
    out = set()
    for tok in NUM.findall(text):
        clean = tok.replace(",", "").replace("−", "-").rstrip(".")
        if clean and clean != "-":
            out.add(clean)
    return out


def flatten(obj, acc: set[str]):
    """Every numeric leaf in facts.json, in the string forms prose might use."""
    if isinstance(obj, dict):
        for v in obj.values():
            flatten(v, acc)
    elif isinstance(obj, list):
        for v in obj:
            flatten(v, acc)
    elif isinstance(obj, bool):
        pass
    elif isinstance(obj, (int, float)):
        from decimal import Decimal, ROUND_HALF_UP
        f = float(obj)
        acc.add(str(obj))
        acc.add(f"{f:g}")
        # Prose rounds, and it may round half-up where Python's format rounds
        # half-even (18.5645 -> "18.564" or "18.565"). Accept both, and the
        # absolute value, since sign is often carried by words instead.
        for nd in range(0, 7):
            q = Decimal(1).scaleb(-nd)
            for val in (f, abs(f), f * 100, abs(f) * 100):
                acc.add(f"{val:.{nd}f}")
                try:
                    acc.add(str(Decimal(repr(val)).quantize(q, rounding=ROUND_HALF_UP)))
                except Exception:
                    pass
        if f == int(f):
            acc.add(str(int(f)))
    elif isinstance(obj, str):
        acc.update(numbers_in(obj))


def main() -> int:
    if not os.path.exists(FACTS_PATH):
        print("facts.json not found — run docs/figures/make_figures.py first")
        return 1

    with open(FACTS_PATH, encoding="utf-8") as f:
        facts = json.load(f)

    known: set[str] = set()
    flatten(facts, known)
    known |= {n.lstrip("-") for n in known}

    # Derived quantities the prose legitimately computes from other facts.
    derived = {
        "97.6",                          # share of explanatory power lost with lag 0 removed
        str(facts["n_daily"] - 1),       # number of returns = observations - 1
        # Display floor, not a claim. A p-value that rounds to 0.0 is written
        # "< 0.0001" rather than "0.0000", because a test never reports that a
        # result is exactly impossible. The frontend's pval() does the same.
        "0.0001",
    }
    known |= derived

    failures = []
    for doc in DOCS:
        path = os.path.join(HERE, doc)
        if not os.path.exists(path):
            continue
        text = open(path, encoding="utf-8").read()
        # Strip everything that carries numbers which are not claims about the
        # data: code blocks, YAML front matter, image paths, Marp sizing hints,
        # CSS colours, the bibliography (page and volume numbers), section
        # cross-references, and ARIMA order tuples.
        text = re.sub(r"```.*?```", "", text, flags=re.S)
        text = re.sub(r"^---$.*?^---$", "", text, flags=re.S | re.M)
        text = re.sub(r"!\[[^\]]*\]\([^)]*\)", "", text)
        text = re.sub(r"\bw:\d+\b", "", text)
        text = re.sub(r"#[0-9a-fA-F]{3,8}\b", "", text)
        text = re.sub(r"^# References.*?(?=^# |\Z)", "", text, flags=re.S | re.M)
        text = re.sub(r"§\s*\d+(\.\d+)*", "", text)
        text = re.sub(r"^#+ *\d+(\.\d+)*", "", text, flags=re.M)
        text = re.sub(r"\b(?:Section|Part|Figure|Table)s?\s+\d+(\.\d+)*", "", text)
        text = re.sub(r"\d{4}-\d{2}-\d{2}", "", text)          # ISO dates
        text = re.sub(r"^\s*\*\*(?:Slides|Dashboard tab|Report):\*\*.*$", "",
                      text, flags=re.M)                        # presenter cross-refs
        text = re.sub(r"\(\s*\d\s*,\s*\d\s*,\s*\d\s*\)", "", text)
        text = re.sub(r"ARIMA\(\d,\d,\d\)", "", text)
        text = re.sub(r"`[^`]*`", "", text)        # inline code: ports, commands
        text = re.sub(r"^\*\*\d+\.\s", "", text, flags=re.M)   # numbered list markers
        text = re.sub(r"\b0\d\b", "", text)        # zero-padded tab numbers (01..05)

        for tok in sorted(numbers_in(text)):
            bare = tok.lstrip("-")
            if bare in IGNORE or bare in known or tok in known:
                continue
            failures.append((doc, tok))

    if failures:
        print(f"{len(failures)} number(s) not traceable to facts.json:\n")
        for doc, tok in failures:
            print(f"  {doc:26s} {tok}")
        print("\nEither the prose is stale, or make_figures.py needs re-running.")
        return 1

    print(f"OK — every number in {', '.join(DOCS)} traces to facts.json "
          f"({len(facts)} facts).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
